stages:
  - 2021 testing
  - 2022 testing

.Unit_Tests:
  artifacts:
    when: always
    reports:
      junit: "**/CodeCoverage/*.xml"

Unit Tests C#:
  image: mcr.microsoft.com/dotnet/sdk:5.0.402-focal-amd64
  stage: 2021 testing
  extends: .Unit_Tests
  script:
    - cd 2021/Nyk
    - dotnet test AdventOfTest -p:CollectCoverage=true -p:Threshold=80 --configuration Debug --test-adapter-path:"AdventOfTest/" --logger:"junit;LogFilePath=..\CodeCoverage\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
  only:
    refs:
      - branches
      - merge_requests
    changes:
      - "2021/Nyk/*.cs"

Unit Tests Python:
  stage: 2022 testing
  extends: .Unit_Tests