stages:
  - testing

.Unit_Tests:
  artifacts:
    reports:
      cobertura: "**/CodeCoverage/coverage.cobertura.xml"

Unit Tests C#:
  image: mcr.microsoft.com/dotnet/sdk:5.0.402-focal-amd64
  stage: testing
  extends: .Unit_Tests
  script:
    - cd 2021/Nyk
    - dotnet test AdventOfTest -p:CollectCoverage=true -p:CoverletOutputFormat=cobertura -p:CoverletOutput='../CodeCoverage/' -p:Threshold=95 --configuration Debug
  except:
    - main
