stages:
  - 2021 testing
  - 2022 testing

.python_jobs_nyk:
  image: python:3.10-alpine
  before_script:
    - apk --no-cache add curl
    - apk add just
    - curl -sSL https://install.python-poetry.org | python -
    - export PATH="/root/.local/bin:$PATH"
    - poetry config virtualenvs.in-project true
    - cd 2022/Nyk
  cache:
    key: $CI_COMMIT_BRANCH
    paths:
      - 2022/Nyk/.venv
    policy: pull


.unit_tests:
  artifacts:
    when: always
    reports:
      junit: "**/CodeCoverage/*.xml"

unit_tests_C#:
  image: mcr.microsoft.com/dotnet/sdk:5.0.402-focal-amd64
  stage: 2021 testing
  extends: .unit_tests
  script:
   - cd 2021/Nyk
   - dotnet test AdventOfTest -p:CollectCoverage=true -p:Threshold=80 --configuration Debug --test-adapter-path:"AdventOfTest/" --logger:"junit;LogFilePath=..\CodeCoverage\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
  rules:
    - changes:
        paths:
          - "2021/Nyk/*.cs"
  needs: []

poetry_install_nyk:
  stage: 2022 testing
  extends:
   - .python_jobs_nyk
  script: just install
  cache:
    policy: pull-push
  needs: []

unit_tests_python_nyk:
  stage: 2022 testing
  extends:
   - .unit_tests
   - .python_jobs_nyk
  script:
   - just test
  rules:
    - changes:
        paths:
          - "2022/Nyk/*.py"
  needs: [poetry_install_nyk]