install:
    poetry install

local: install
    poetry run pre-commit install

update:
    poetry update

black:
    poetry run black . --check --diff

black-fix:
    poetry run black .

flake8:
    poetry run flake8

isort:
    poetry run isort . --check --diff

isort-fix:
    poetry run isort .

lint: black flake8 isort

lint-fix: black-fix isort-fix

test:
    poetry run pytest \
    --junitxml=coverage/junit.xml tests/ -ra -s

test-vv:
    poetry run pytest tests/ -junitxml=coverage/junit.xml -vv

run-day day part:
    poetry run python -m day0'{{day}}'.part_'{{part}}'

gen-day day:
    poetry run python utils/generate/generate_day.py '{{day}}'
